### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by KayBeSee** [darosior/clightningjs#4]
Hey --

I am trying to write a plugin for my C-Lightning node in Javascript and came across this library.

I tried to get the Hello World example up and running but I am struggling a bit.

My first question (and this might be stupid) is do I need node and npm installed on the device that my node is running on? I assume yes, but want to make sure.

Once that's cleared, I assume I can clone my repo, npm install, and then run `lightningd --plugin=/data/lightning/plugins/clightning-plugin-sandbox`, correct?

Thank you!

**Comment by darosior** [comment]
Hi @KayBeSee just seeing the issue now since you closed it, could you succesfully experiment with clightningjs ?
